remote_theme: just-the-docs/just-the-docs
color_scheme: custom
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Sunlix Documentation
description: Official documentation for Sunlix projects.
